### ISSUE TITLE
Segmentation fault when importing Shapefile the second time

### ISSUE THREAD

**Issue by dt99jay** [domlysz/BlenderGIS#53]
When calling the BlenderGIS addon from my own script, I'm getting a segmentation fault when importing a Shapefile for the second time (it works fine the first time).

Here's a minimal example:

```
import bpy
from os.path import abspath, dirname
from bpy import context

bpy.ops.importgis.shapefile("INVOKE_DEFAULT", filepath = abspath(dirname(__file__))+"/shapefile.shp", shpCRS="EPSG:27700", fieldElevName="ELEV", separateObjects = False) # Works fine

bpy.ops.importgis.shapefile("INVOKE_DEFAULT", filepath = abspath(dirname(__file__))+"/shapefile.shp", shpCRS="EPSG:27700", fieldElevName="ELEV", separateObjects = False) # Causes Blender to crash
```

I'm using Blender 2.78 on Mac OS 10.12.1. Here's the terminal output:

```
Jamies-MBP:Documents jamie$ /Applications/blender.app/Contents/MacOS/blender -b -noaudio -P Minimal.py
Read new prefs: /Users/jamie/Library/Application Support/Blender/2.78/config/userpref.blend
found bundled python: /Applications/blender.app/Contents/MacOS/../Resources/2.78/python
Exception in module register(): '/Users/jamie/Library/Application Support/Blender/2.78/scripts/addons/BlenderGIS-master/__init__.py'
Traceback (most recent call last):
  File "/Applications/blender.app/Contents/MacOS/../Resources/2.78/scripts/modules/addon_utils.py", line 349, in enable
    mod.register()
  File "/Users/jamie/Library/Application Support/Blender/2.78/scripts/addons/BlenderGIS-master/__init__.py", line 131, in register
    km = wm.keyconfigs.active.keymaps['3D View']
AttributeError: 'NoneType' object has no attribute 'keymaps'
Read shapefile...
Feature type : PolyLine
0%, 10%, 20%, 30%, 40%, 50%, 60%, 70%, 80%, 90%, 100%
Build in 0.404313 seconds
Read shapefile...
Feature type : PolyLine
0%, 10%, 20%, 30%, 40%, 50%, 60%, 70%, 80%, 90%, 100%
Build in 1.482001 seconds
Writing: /var/folders/c2/wz9svkyd1qv1lpnzbcpvbxlr0000gn/T/blender.crash.txt
Segmentation fault: 11
```

[blender.crash.txt](https://github.com/domlysz/BlenderGIS/files/614170/blender.crash.txt) is attached, along with a zip of [the Shapefile](https://github.com/domlysz/BlenderGIS/files/614174/Shapefile.zip) (I get the same error with various Shapefiles).

**Comment by dt99jay** [comment]
Just tried the above script with Blender 2.77 – no problems at all. Perhaps there is [some change in 2.78](https://wiki.blender.org/index.php/Dev:Ref/Release_Notes/2.78/Add-ons#Blender_2.78:_Py_API_.26_Add-ons) that breaks this part of BlenderGIS?

**Comment by domlysz** [comment]
Hi,

Work great for me with 2.78 on linux. I will try it on Windows tomorrow  but I don't think the problem come from BlenderGIS side
